### PR TITLE
devops: add github actions

### PR DESCRIPTION
**Pull request by Meir017**

### CODE REVIEW

**Comment by Meir017** [comment]
looks like the tests are not passing on linux, see https://github.com/sharpliner/sharpliner/actions/runs/11592082154/job/32273200691?pr=337

expected:
```yaml
jobs:
- job: test
  steps:
  - powershell: |+
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"

  - powershell: |+
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"

  - powershell: |-
      Connect-AzContext
      Set-AzSubscription --id foo-bar-xyz

  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: foo.ps1

  - powershell: |+
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"
```

actual:

```yml
jobs:
- job: test
  steps:
  - powershell: |
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"

  - powershell: |
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"

  - powershell: |-
      Connect-AzContext
      Set-AzSubscription --id foo-bar-xyz

  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: foo.ps1

  - powershell: |
      Set-ErrorActionPreference Stop
      Write-Host "Lorem ipsum dolor sit amet"
```

**Comment by Meir017** [comment]
now the pipeline is failing due to the step 

```yml
  - task: DotNetCoreCLI@2
    displayName: Build project reference test
    inputs:
      command: build
      projects: tests/E2E.Tests/ProjectUsingTheLibrary/E2E.Tests.ProjectUsingTheLibrary.csproj
      includeNuGetOrg: false
      workingDirectory: tests/E2E.Tests
```

I think this is the issue -
in azure-pipelines the Dotnet cli command has an input `workingDirectory` which only affects the dotnet command but doesn't affect the working-directory of the powershell script `clean-dependencies.ps1`

**Comment by premun** [comment]
What is the point of introducing this check? To me it's another thing we would have to maintain but brings no additional value I think?

For the record, we still need to have the Azure Pipelines for these reasons:
- It tests the library itself
- We have the publisher pipeline that pushes the package to nuget.org after a release

Oh and I found out the problems with AzDO the other day was an actual outage between AzDO and GitHub. It hit us pretty hard actually.

**Comment by Meir017** [comment]
> Oh and I found out the problems with AzDO the other day was an actual outage between AzDO and GitHub. It hit us pretty hard actually.

Just fir this reason:) not sure about this

**Comment by premun** [comment]
Okay, then, I guess we can close this one then

**Pull request closed without merging**
