### PR TITLE
Rename `TemplateParameter` to `Parameter`

### PR DESCRIPTION
**Pull request by premun**
Related to the discussion in #208:
- Internal rename of classes since we use parameters even in pipelines and not just templates
- Make display name optional for pipeline parameters

### CODE REVIEW

**Comment by premun** [comment]
cc @brunskutscher

**Comment by brunskutscher** [comment]
on preparing the gh stuff ... it's new to me.

Am Mo., 11. Juli 2022 um 23:08 Uhr schrieb Přemek Vysoký <
***@***.***>:

**Comment by brunskutscher** [comment]
not sleeping ...
i test this with my "pipeline requirements".

Am Mo., 11. Juli 2022 um 23:08 Uhr schrieb Přemek Vysoký <
***@***.***>:

**Comment by premun** [comment]
Hey @brunskutscher,
Any updates? This change doesn't contain that much of a functional change btw (more of an internal renames)

**Comment by brunskutscher** [comment]
tried it with my example project ...
dont know the right way of adding review comments ...
one finding so far:
parameters are rendered  after stages ... not sure why.
will work on this tomorrow.

mfg
matthias


Am Do., 4. Aug. 2022 um 12:36 Uhr schrieb Přemek Vysoký <
***@***.***>:

**Comment by premun** [comment]
I tried to generate a pipeline and parameters were on top. What kind of pipeline were you generating? Can you share the code?

You can comment through GitHub's web: https://github.com/sharpliner/sharpliner/pull/211/files

**Comment by brunskutscher** [comment]
hi,

the problem with the parameter serialization was because of mistake on my
side (trouble updating the 43.43.43 version).
i can confirm that the parameters section is on top.
i had some problems to rebuild the package again:
"
C:\Users\z000g0xn\.nuget\packages\sharpliner\43.43.43\build\Sharpliner.targets(20,5):
error MSB4062: The "Sharpliner.PublishDefinitions" task could not be loaded
from the assembly
C:\Users\z000g0xn\.nuget\packages\sharpliner\43.43.43\build\..\lib\net5.0\Sharpliner.dll.
Could not load file or assembly 'YamlDotNet, Version=11.0.0.0,
Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find
the file specified. Confirm that the <UsingTask> declaration is correct,
that the assembly and all its dependencies are available, and that the task
contains a public class that implements Microsoft.Build.Framework.ITask.
[C:\Temp\rev\sharpliner\eng\Sharpliner.CI\Sharpliner.CI.csproj]
"
the problem is only with 5.0 ...

i have no additional review comments. should i add a "N/A" (or whatever) as
a comment to the individual files?


Am Mo., 8. Aug. 2022 um 20:18 Uhr schrieb Přemek Vysoký <
***@***.***>:

**Comment by premun** [comment]
@brunskutscher this is a problem that I just fixed in main. I merged main into this PR so please `git pull` and give it another try.

Try the steps mentioned here: https://github.com/sharpliner/sharpliner#developing-sharpliner
```
dotnet clean eng/Sharpliner.CI/Sharpliner.CI.csproj
dotnet build eng/Sharpliner.CI/Sharpliner.CI.csproj
```

**Comment by premun** [comment]
I think we can merge this then, I will want to release a new version later tonight

**Pull request merged**
