### PR TITLE
Make `PipelineBase.Validations` public

### LINKED ISSUE #294: Allow overriding PipelineBase.Validation in subclasses outside of the Sharpliner project
### Issue

Libraries that depend on Sharpliner and subclass from `PipelineBase` cannot override `Validations` as it is marked internal.

```
    /// <summary>
    /// Returns the list of validations that should be run on the definition (e.g. wrong dependsOn, artifact name typos..).
    /// </summary>
    internal abstract IReadOnlyCollection<IDefinitionValidation> Validations { get; }
```

### Goal

Make it public.

### PR DESCRIPTION
**Pull request by aditnryn**
Fixes #294

### CODE REVIEW

**Review by premun — APPROVED** [review]

**Comment by aditnryn** [comment]
@premun Need your assistance here. I cannot make sense of the build failure. The change should not introduce any change in the published YAML pipeline (publish.yml).

**Comment by premun** [comment]
@aditnryn maybeeee it's serializing the new member?

Is there a diff if you build locally to the YAMLs?

**Comment by premun** [comment]
I am having a look today

**Comment by premun** [comment]
Ah, yeah, it's the validations being serialized too:

```
validations:
- {}
- {}
- {}
```

**Pull request merged**
